server:
  port: 8888

spring:
  application:
    name: tt-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mrTwice/2025-05-otus-spring-Yampolskiy-attestation.git
          default-label: tt-mvp
          clone-on-start: true

logging:
  level:
    org.springframework.security: DEBUG