spring:
  application:
    name: tt-task-service
  cloud:
    config:
      retry:
        max-attempts: 10
        initial-interval: 1000   # 1s
        max-interval: 5000       # 5s
        multiplier: 1.5
      username: config-client-task-service
      password: config-secret-task